// src/pages/Guarantee/Settlement.jsx
import React, { Component } from "react";
import { connect } from "react-redux";
import { t } from "../../locale/locales";
import { SettlementStyled } from "./styled";
import { settleable, burn, settle } from "../../abi/factory";
import { web3 as Web3 } from "../../abi";
import { getBalance } from "../../abi/order";
import { getWei, getSymbol, getID, wrapperAdress } from "../../static/utils/AdressPool";
import { add, mul } from "../../static/utils/calculate";
import precision from "../../static/utils/precision";

export class Settlement extends Component {
  constructor() {
    super();
    this.state = {
      settlement_list: [],
    };
  }

  componentDidMount() {
    this.getsettlementList();
  }

  getsettlementList = async () => {
    const web3 = await Web3();
    setTimeout(async () => {
      // let data = JSON.parse(window.localStorage.getItem("long_map"));
      let data = JSON.parse(window.localStorage.getItem("about_info_shell"));
      // 转换成数组
      let data_arr = [];
      for (const key in data) {
        if (data.hasOwnProperty(key)) {
          data_arr.push(data[key]);
        }
      }
      const charID = await getID()
      // console.log("wrapperAdress('LONG', charID)#####", wrapperAdress('LONG', charID));
      // let testAddress = '0x0603CD787f45D1b830cEd5AcaEECDaB661B267ca';
      // console.log('data####', data);
      // 过滤数据
      let new_data = data_arr.filter((item) => {
        // return true;
        // if (charID === 1) return true
        // if (item.count < 63) {
        //   return false;
        // }
        // console.log('web3.currentProvider.selectedAddress####', web3.currentProvider.selectedAddress);
        // if (!web3.currentProvider.selectedAddress) return false;
        // if (
        //   item.creator.toLowerCase() ===
        //   web3.currentProvider.selectedAddress.toLowerCase()
        //   // testAddress.toLowerCase()
        // ) {
        //   return true;
        // }
        // return false;
        if (
          item.seller.toLowerCase() ===
          web3.currentProvider.selectedAddress.toLowerCase()
          // testAddress.toLowerCase()
        ) {
          return true;
        }
      });
      // let arr = []
      const  promiseArr = [];
      const result = [];
      let longBalance;
      let shortBalance, _collateral, _underlying, item;
      // new_data.forEach(async (item) => {
      for (let i = 0; i < new_data.length; i ++) {
        item = new_data[i];
        _collateral = getSymbol(item.longInfo._collateral, charID)[0];
        longBalance = await getBalance(item.longInfo.long, _collateral);
        _underlying = getSymbol(item.longInfo._underlying, charID)[0];
        shortBalance = await getBalance(item.longInfo.short, _collateral);
        if (Number(shortBalance) > 0 && Number(longBalance) > 0) {
          result.push({
            creator: item.seller,
            _collateral,
            _underlying,
            col: 0,
            fee: 0,
            // und: web3.utils.fromWei(res.und, getWei(item._underlying, charID)),
            und: 0,
            long: item.longInfo.long,
            short: item.longInfo.short,
            longBalance: longBalance,
          });
        } 
        let number = Number(shortBalance) - Number(longBalance);
        if (number > 0) {
          
          // number = web3.utils.toBN(String(number));
          // console.log('number######', String(number));
          try {
            let volume = web3.utils.toWei(String(number), getWei(_collateral, charID));
            const settle = await settleable(item.longInfo.short, volume);
            if (settle.col !== "0" || settle.und !== "0") {
              result.push({
                creator: item.seller,
                _collateral,
                _underlying,
                col: web3.utils.fromWei(settle.col, getWei(item.longInfo._collateral, charID)),
                fee: web3.utils.fromWei(settle.fee, getWei(item.longInfo._collateral, charID)),
                und: web3.utils.fromWei(settle.und, getWei(item.longInfo._collateral, charID)),
                long: item.longInfo.long,
                short: item.longInfo.short,
                longBalance: Number(longBalance) > 0 ? String(number) : 0,
              });
            }
          } catch(err) {}
        } 
      }
      this.setState({
        settlement_list: result,
      }); 

      // });
      return;
      // Promise.all(
      //   new_data.map(async (item) => {
      //     try {
      //       console.log('item.short####', item.short);
      //       const res = await settleable(item.creator, item.short);
      //       let _collateral = getSymbol(item._collateral, charID)[0];
      //       const longBalance = await getBalance(item.long, _collateral);
      //       console.log('longBalance#####', longBalance);
      //       let _underlying = getSymbol(item._underlying, charID)[0];
      //       const shortBalance = await getBalance(item.short, _underlying);
      //       console.log('shortBalance#####', shortBalance);
      //       if (longBalance !== "0" && shortBalance !== "0") {
      //         return (item = {
      //           creator: item.creator,
      //           _collateral: getSymbol(item._collateral, charID)[0],
      //           _underlying: getSymbol(item._underlying, charID)[0],
      //           col: web3.utils.fromWei(res.col, getWei(item._collateral, charID)),
      //           fee: web3.utils.fromWei(res.fee, getWei(item._collateral, charID)),
      //           // und: web3.utils.fromWei(res.und, getWei(item._underlying, charID)),
      //           und: shortBalance,
      //           long: item.long,
      //           short: item.short,
      //           longBalance: longBalance,
      //         });
      //         // arr.push(item)
      //       }
      //       if (res.col !== "0" || res.und !== "0") {
      //         return (item = {
      //           creator: item.creator,
      //           _collateral: getSymbol(item._collateral, charID)[0],
      //           _underlying: getSymbol(item._underlying, charID)[0],
      //           col: web3.utils.fromWei(res.col, getWei(item._collateral, charID)),
      //           fee: web3.utils.fromWei(res.fee, getWei(item._collateral, charID)),
      //           und: web3.utils.fromWei(res.und, getWei(item._underlying, charID)),
      //           long: item.long,
      //           short: item.short,
      //           longBalance: 0,
      //         });
      //         // arr.push(item)
      //       }
      //       // let _collateral = getSymbol(item._collateral, charID)[0];
      //       // const longBalance = await getBalance(item.long, _collateral);
      //       // if (longBalance !== "0") {
      //       //   return (item = {
      //       //     creator: item.creator,
      //       //     _collateral: getSymbol(item._collateral, charID)[0],
      //       //     _underlying: getSymbol(item._underlying, charID)[0],
      //       //     col: web3.utils.fromWei(res.col, getWei(item._collateral, charID)),
      //       //     fee: web3.utils.fromWei(res.fee, getWei(item._collateral, charID)),
      //       //     und: web3.utils.fromWei(res.und, getWei(item._underlying, charID)),
      //       //     long: item.long,
      //       //     short: item.short,
      //       //     longBalance: longBalance,
      //       //   });
      //       //   // arr.push(item)
      //       // }
      //     } catch (error) {

      //     }
      //   })
      // ).then((res) => {
      //   const list = res.filter((r) => r);
      //   this.setState({
      //     settlement_list: list,
      //   });
      // });
    }, 300);

  };

  handelClickSettle = async (item, index) => {
    // return;
    if (item.longBalance != 0) {
      // burn
      burn(
        item.short,
        item.longBalance,
        { _collateral: item._collateral },
        (status) => {
          console.log(status);
        }
      );
    } else {
      // 正常结算
      settle(item.short, (status) => {
        console.log(status);
        // let item_status = ''
        // switch (status) {
        //   case 'pending':
        //     item_status = 'active'
        //     break;
        //   case 'approve':
        //     item_status = 'active'
        //     break;

        //   default:
        //     item_status = ''
        //     break;
        // }
        // let list = this.state.settlement_list
        // list[index].status = 'active'
        // this.setState({
        //   settlement_list: list
        // })
      });
    }


  };

  render() {
    return (
      <SettlementStyled>
        <h1>{t("t107")}</h1>
        <table>
          <thead>
            <tr>
              <th>Type</th>
              <th>underlying</th>
              <th>collaborate</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {this.state.settlement_list.length === 0 ?
              <tr className='queshen_tr'>
                <td className='quesheng'>
                  <img src="/assets/images/queshen.png" alt="" />
                  <p>No undrawn funds</p>
                </td>
              </tr> : <tr></tr>
            }
            {this.state.settlement_list.map((item, index) => {
              return (<tr key={index + 'a'}>
                <td>
                  <img
                    className='un_logo'
                    src={`/assets/images/${item._underlying}@2x.png`}
                    alt=""
                  />
                  <h5>{item._underlying}</h5>
                </td>
                <td>{mul(item.und, 1)} {item._underlying}</td>
                {/* <td>{item.col} {item.longBalance} {add(item.col, item.longBalance)} {item._collateral}</td> */}
                <td>{precision.plus(item.col, item.longBalance)} {item._collateral}</td>
                <td>
                  <button
                    className={item.state === 'active' ? 'active' : ''}
                    onClick={() => {
                      this.handelClickSettle(item, index);
                    }}>Claim</button>
                </td>
              </tr>)
            })}


          </tbody>
        </table>

      </SettlementStyled>
    );
  }
}

const mapStateToProps = (state) => ({});

const mapDispatchToProps = {};

export default connect(mapStateToProps, mapDispatchToProps)(Settlement);

// components/settlement/index.vue
<template>
  <div class="settlement">
    <h3 class="title">Funds to e withdrawn</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Type</th>
          <th>Underlying</th>
          <th>Collaborate</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(item, index) in settlementList" :key="index">
          <td>
            <div class="settlement-type-box">
              <img :src="require(`~/assets/img/${item._underlying}@2x.png`)" />
              <span>{{ item._underlying }}</span>
            </div>
          </td>
          <td>
            {{ addCommom(item.und, 4) }}
            {{ item._underlying }}
          </td>
          <td>
            {{ addCommom(precision.plus(item.col, item.longBalance), 4) }}
            {{ item._collateral }}
          </td>
          <td>
            <button
              @click="toSettle(item, index)"
              :class="currentClaimId === index ? 'button-loading' : ''"
              :disabled="currentClaimId === index ? true : false"
            >
              <img
                src="~/assets/img/loading.gif"
                v-if="currentClaimId === index"
              />Claim
            </button>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="h5-table">
      <div
        class="h5-table-item"
        v-for="(item, index) in settlementList"
        :key="index"
      >
        <div class="h5-table-top">
          <p>
            <img :src="require(`~/assets/img/${item._underlying}@2x.png`)" />
            <span>{{ item._underlying }}</span>
          </p>
          <button
            @click="toSettle(item, index)"
            :class="currentClaimId === index ? 'button-loading' : ''"
            :disabled="currentClaimId === index ? true : false"
          >
            <img
              src="~/assets/img/loading.gif"
              v-if="currentClaimId === index"
            />Claim
          </button>
        </div>
        <div class="h5-table-bottom">
          <p>
            {{ addCommom(precision.times(item.und, 1), 4) }}
            <i>{{ item._underlying }}</i>
          </p>
          <p>
            {{ addCommom(precision.plus(item.col, item.longBalance), 4) }}
            <i>{{ item._collateral }}</i>
          </p>
        </div>
      </div>
    </div>
    <NoData v-if="settlementList.length < 1 && !isLoading"></NoData>
    <div class="loading" v-if="isLoading">
      <img src="~/assets/img/loading.gif" />
    </div>
    <div class="page" v-if="originList.length >= 5">
      <div :class="['pre', page === 1 ? 'disabled' : '']" @click="preFun"></div>
      <div
        :class="[
          'next',
          page === parseInt(originList.length / limit) + 1 ? 'disabled' : '',
        ]"
        @click="nextFun"
      ></div>
    </div>
  </div>
</template>
<script>
import NoData from "~/components/common/no-data.vue";
import { getBalance } from "~/interface/order.js";
import { newGetSymbol, getWei } from "~/assets/utils/address-pool.js";
import { toWei, fromWei } from "~/assets/utils/web3-fun.js";
import { settleable, burn, settle } from "~/interface/factory.js";
import precision from "~/assets/js/precision.js";
import { fixD, addCommom } from "~/assets/js/util.js";

export default {
  name: "settlement",
  components: {
    NoData,
  },
  data() {
    return {
      originList: [],
      settlementList: [],
      precision: precision,
      isLoading: false,
      offset: 0,
      limit: 5,
      page: 1,
      addCommom: addCommom,
    };
  },
  computed: {
    myAboutInfoSell() {
      return this.$store.state.myAboutInfoSell;
    },
    currentClaimId() {
      return this.$store.state.currentAllId.currentClaimId;
    },
  },
  watch: {
    myAboutInfoSell: {
      handler: "myAboutInfoSellWatch",
      immediate: true,
    },
  },
  methods: {
    preFun() {
      if (this.offset > 0) {
        this.offset = this.offset - this.limit;
        this.page = this.page - 1;
        this.searchList();
      } else {
        this.offset = 0;
      }
    },
    nextFun() {
      const total = this.originList.length;
      if (this.offset < total) {
        this.offset = this.offset + this.limit;
        this.page = this.page + 1;
        this.searchList();
      }
    },
    myAboutInfoSellWatch(newValue) {
      if (newValue) {
        this.setSettlementList(newValue);
      }
    },
    async setSettlementList(list) {
      this.isLoading = true;
      const result = [];
      let item,
        longBalance,
        shortBalance,
        _collateral,
        _underlying,
        number,
        volume,
        id;
      for (let i = 0; i < list.length; i++) {
        item = list[i];
        _collateral = newGetSymbol(item.longInfo._collateral, window.chainID);
        longBalance = await getBalance(item.longInfo.long, _collateral);
        _underlying = newGetSymbol(item.longInfo._underlying, window.chainID);
        shortBalance = await getBalance(item.longInfo.short, _collateral);
        // console.log(i + '####item###', item);
        // console.log(i + '####longBalance###',longBalance, '###shortBalance###', shortBalance );
        if (Number(shortBalance) > 0 && Number(longBalance) > 0) {
          result.push({
            creator: item.seller,
            _collateral,
            _underlying,
            col: 0,
            fee: 0,
            und: 0,
            long: item.longInfo.long,
            short: item.longInfo.short,
            longBalance: longBalance,
          });
        }

        number = precision.minus(shortBalance, longBalance);

        if (Number(number) > 0) {
          try {
            volume = toWei(number, _collateral);
            const settle = await settleable(item.longInfo.short, volume);

            if (settle.col !== "0" || settle.und !== "0") {
              result.push({
                creator: item.seller,
                _collateral,
                _underlying,
                col: fromWei(settle.col, _collateral),
                fee: fromWei(settle.fee, _collateral),
                und: fromWei(settle.und, _collateral),
                long: item.longInfo.long,
                short: item.longInfo.short,
                // longBalance: Number(longBalance) > 0 ? String(number) : 0,
                longBalance: 0,
              });
            }
          } catch (err) {
            console.log("setSettlementList##err###", err);
          }
        }
      }
      this.isLoading = false;
      // this.settlementList = result;
      this.originList = result;
      this.settlementList = result.slice(0, this.limit);
      this.$store.dispatch("setCurrentId", { currentClaimId: '' });
    },
    searchList() {
      this.settlementList = this.originList.slice(
        this.offset,
        this.limit * this.page
      );
    },
    toSettle(item, index) {
      console.log(item);
      this.$store.dispatch("setCurrentId", { currentClaimId: index });
      if (item.longBalance != 0) {
        burn(
          item.short,
          item.longBalance,
          { _collateral: item._collateral },
          item
        );
      } else {
        settle(item.short, item);
      }
    },
  },
};
</script>

<style lang="scss" scoped>
@import "~/assets/css/base.scss";

@media screen and (min-width: 750px) {
  .settlement {
    background: $bg-c;
    margin-top: 20px;
    /* width: 1200px;
    margin: 0 auto; */
    margin-bottom: 30px;
    padding-bottom: 20px;
    position: relative;
    .title {
      font-size: 16px;
      color: $text-t;
      height: 60px;
      line-height: 60px;
      padding-left: 16px;
    }
    .settlement-type-box {
      display: flex;
      align-items: center;
      img {
        width: 50px;
        height: 32px;
      }
      span {
        margin-left: 6px;
      }
    }
    .h5-table {
      display: none;
    }
  }
}
@media screen and (max-width: 750px) {
  .settlement {
    background: $bg-c;
    margin-bottom: 20px;
    .title {
      font-size: 14px;
      color: $text-t;
      height: 60px;
      line-height: 60px;
      padding-left: 16px;
      box-shadow: 0px 1px 0px 0px #1d1d1d;
    }
    .table {
      display: none;
    }
    .h5-table {
      .h5-table-item {
        padding: 16px 20px 16px;
        box-shadow: 0px 1px 0px 0px #1d1d1d;
      }
      .h5-table-top {
        display: flex;
        justify-content: space-between;
        p {
          display: flex;
          align-items: center;
          img {
            width: 48px;
            height: 30px;
          }
          span {
            font-size: 20px;
            font-weight: 500;
            color: #dbdbdb;
          }
        }
        > button {
          display: flex;
          padding: 6px 12px;
          background: #873232;
          border-radius: 10px;
          align-items: center;
          color: $text-m;
          img {
            width: 16px;
            height: 16px;
            margin-right: 2px;
          }
        }
        > button:hover {
          background: $main-hover;
        }
      }
      .h5-table-bottom {
        display: flex;
        margin-top: 15px;
        justify-content: space-between;
        p {
          font-size: 16px;
          font-weight: 500;
          color: #dbdbdb;
          i {
            font-size: 14px;
            color: #7d7d7d;
            line-height: 20px;
          }
        }
      }
    }
    .settlement-type-box {
      display: none;
    }
  }
}
</style>
